newsapp/urls.py
from django.urls import path, include

from . import views
from django.contrib.auth import views as auth_views

app_name = 'newsapp'
urlpatterns = [
    path('', views.index, name='index'),
    
    path('signin/',views.signin, name='signin'),
    path('login/', auth_views.LoginView.as_view(template_name='newsapp/signin.html')),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),

    path('news-articles/', views.news_articles, name='news_articles'),
    path('news-articles/<int:news_id>/', views.news_article_detail, name='news_article_detail'),
    path('authors/', views.authors, name='authors'),
    path('authors/<int:author_id>/', views.author_detail, name='author_detail'),
    path('trending/', views.trending, name='trending'),
    path('my/', views.mypage, name='mypage'),
    path('my/create/', views.create, name='create'),
]

purduenews/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('CNIT581-048-project3/', include('newsapp.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newsapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User as auth_User

# Create your models here.

class User(models.Model):
	# User_ID <-- built-in ID
	user = models.OneToOneField(auth_User, on_delete=models.CASCADE)
	# username = models.CharField(max_length=50)
	# email = models.CharField(max_length=100)
	# fname = models.CharField(max_length=50)
	# lname = models.CharField(max_length=50)

	def __str__(self):
		return " ID: "+str(self.id)+" -- "+self.user.username

class News_Article(models.Model):
	# Article_ID <-- built-in ID
	title = models.CharField(max_length=200)
	# Author_ID will be a Foreign Key referring to the user table
	author = models.ForeignKey(User, on_delete=models.PROTECT) # when a user is deleted, the article will not be deleted
	content = models.TextField(blank=False) #A large text field. The default form widget for this field is a Textarea.
	creation_time = models.DateTimeField(auto_now_add=True) #Automatically set the field to now when the object is first created. 
	last_modified = models.DateTimeField(auto_now=True) #Automatically set the field to now every time the object is saved with .save()
	likes = models.IntegerField(default=0)
	non_empty = models.TextField(null=False)
	# demo_date = models.DateTimeField(default=timezone.now())

	def __str__(self):
		return " ID: "+str(self.id)+" -- "+self.title 


class Comment(models.Model):
	# Comment_ID <-- built-in ID
	commenter = models.ForeignKey(User, on_delete=models.CASCADE) # when a user is deleted, all comments created by this user will be deleted.
	article = models.ForeignKey(News_Article, on_delete=models.CASCADE) # when an article is deleted, all comments about it will be deleted.
	comments = models.TextField() #A large text field. The default form widget for this field is a Textarea.

class Subscription(models.Model):
	subscriber = models.ForeignKey(User, on_delete=models.CASCADE, related_name="subscriber")
	subscribee = models.ForeignKey(User, on_delete=models.PROTECT, related_name="subscribee")
	subscribe_when = models.DateTimeField(auto_now=True)

newsapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.template import loader, RequestContext
from datetime import datetime
import requests
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User as authUser
# Create your views here.

# a view function takes a request and returns a response
# (request handler)
def index(request):
   
    context = {
    "user": request.user,
    'date': '09/28/2021', 
    # "weather": weather_json,
    'featured_today_news': 'Wall Street Journal/Times Higher Education: Purdue tops Big Ten in best value, again among nation\'s best schools',
    
    'featured_news_list': News_Article.objects.all()
    }
    return render(request, 'newsapp/home.html', context)

def signin(request):
    if request.method == "GET":
        return render(request, "newsapp/signin.html", {})
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        return redirect('/CNIT581-048-project3/')
    else:
        # Return an 'invalid login' error message.
        return HttpResponse("Invalid Login")

def signup(request):
    context = {
        # "method": request.method,
        # "post_data": "Not yet",
    }
    if request.method == "POST":
        
        if request.is_ajax():
            # check if user account already exists
            context["username_inuse"] = authUser.objects.filter(username=request.POST['username']).exists()
            return JsonResponse(context)
        else:
            newAuthUser, created_auth = authUser.objects.get_or_create(username = request.POST['username'])
            if created_auth:
                newAuthUser.first_name=request.POST['fname']
                newAuthUser.last_name=request.POST['lname']
                newAuthUser.set_password(request.POST['password'])
                newAuthUser.save()
            newUser, created_user = User.objects.get_or_create(user=newAuthUser)
            user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
            if user is not None:
                login(request, user)
            print(user)
            return redirect('/CNIT581-048-project3/')

    my_response = render(request, 'newsapp/signup.html', context)
    return my_response

def signout(request):
    logout(request)
    print(request.user)
    return redirect('/CNIT581-048-project3/')

def news_article_detail(request, news_id):
    return HttpResponse("You're looking at news article %s." % news_id)

def author_detail(request, author_id):
    return HttpResponse("You're looking at news article %s." % author_id)

def trending(request):
    context = {"trending_news_list":[
        {'id': 1, 'title': 'News Title 1'},
        {'id': 2, 'title': 'News Title 2'},
        {'id': 3, 'title': 'News Title 3'},
        {'id': 4, 'title': 'News Title 4'},
        {'id': 5, 'title': 'News Title 5'},
    ]}
    return render(request, 'newsapp/trending.html', context)

def news_articles(request):
        return HttpResponse("You're looking at the list of all news articles on this site.")

def authors(request):
        return HttpResponse("You're looking at the list of all news articles on this site.")

def mypage(request):
        return HttpResponse("You're looking at the customized page for each user.")

def create(request):
        return HttpResponse("You're creating a news article on this page.")

newsapp/templates/newsapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    {% block title %}<title>Purdue News</title>{% endblock %}
    {% block headReference %}
    <link rel="stylesheet" type="text/css" href="{% static 'newsapp/style.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.13.0/css/all.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'newsapp/scripts.js' %}"></script>
    {% endblock %}
    {% block moreRef %}
    {% endblock %}
</head>
<body>
    {% block test %}
    {% endblock %}
    <div id="title">
        <h1>Purdue News</h1>
    </div>
    
    <div id="subtitle">
        
        <div id="subtitle-links">
            {% block user_status %}

            {% if user.is_authenticated %}
            <p>Welcome, {{ user.first_name }}. 
            <a href="{% url 'newsapp:signout' %}">Sign Out</a>
            </p>
            {% else %}
            <a href="{% url 'newsapp:signin' %}">Sign In</a>
            <a href="{% url 'newsapp:signup' %}">Sign Up</a>
            <br>
            {% endif %}
            
            {% endblock %}
            <input type="text" name="search-box" placeholder="search here ...">
        </div>
        <h2>All important recent University happenings</h2>
    </div>

    <div id="nav-bar">
        <a href="{% url 'newsapp:index' %}" class="selected tab">Home</a>
        <a href="{% url 'newsapp:trending' %}" class="tab">Trending</a>
        <a href="{% url 'newsapp:mypage' %}" class="tab">For you</a>
        <a href="#" id="add-tab">Add Tab</a>
    </div>
    {% block content %}
    <div id="content">
        <div class="left-column">
            <div class="article-container">
                <h3>Featured Today</h3>
                <img id="tmp-loading-img" src="{% static 'newsapp/img/example.gif' %}" alt="this should be a picture for the news article..." style="width: 200px; height: auto;">
                <p id="example-p">{{featured_today_news}}</p>
                <div><i class="far fa-thumbs-up"></i><span>0</span></div>
            </div>
        </div>
        <div class="mid-column">
        {% for featured_news in featured_news_list %}
            <div class="article-container">
                <h4>{{ featured_news.title }}</h4>
                <p><img src="{{ featured_news.img }}">{{ featured_news.content }}</p>
                <div><i class="far fa-thumbs-up"></i><span>{{ featured_news.likes }}</span></div>
            </div>
        {% endfor %}
        </div>
        <div class="right-column">
            <a class="twitter-timeline" href="https://twitter.com/LifeAtPurdue?ref_src=twsrc%5Etfw">Tweets by LifeAtPurdue</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
        <div class="right-column-small">
            <a href="https://twitter.com/LifeAtPurdue?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @LifeAtPurdue</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
    </div>
    {% endblock %}

    <div id="footer">
        <div id="footer-menu">
            <a href="#" class="selected">Home</a> |
            <a href="#">Trending</a> |
            <a href="#">For you</a>
        </div>
        <p>Copyright 2021 All Rights Reserved</p>
    </div>
</body>
</html>

newsapp/templates/newsapp/home.html
{% extends "newsapp/base.html" %}

{% load static %}


{% block moreRef %}
<script src="{% static 'newsapp/ajax_demo.js' %}"></script>
{% endblock %}


{% block content %}
<div id="content">
        <div class="left-column">
            <div class="article-container">
                <h3>Featured Today</h3>
                <img id="tmp-loading-img" src="{% static 'newsapp/img/example.gif' %}" alt="this should be a picture for the news article..." style="width: 200px; height: auto;">
                <p id="example-p">{{featured_today_news}}</p>
                <div><i class="far fa-thumbs-up"></i><span>0</span></div>
            </div>
        </div>
        <div class="mid-column">
        {% for featured_news in featured_news_list %}
            <div class="article-container">
                <h4>{{ featured_news.title }}</h4>
                <p><img src="{{ featured_news.img }}">{{ featured_news.content }}</p>
                <div><i class="far fa-thumbs-up"></i><span>{{ featured_news.likes }}</span></div>
            </div>
        {% endfor %}
        </div>
        <div class="right-column">
            <a class="twitter-timeline" href="https://twitter.com/LifeAtPurdue?ref_src=twsrc%5Etfw">Tweets by LifeAtPurdue</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
        <div class="right-column-small">
            <a href="https://twitter.com/LifeAtPurdue?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @LifeAtPurdue</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
    </div>
{% endblock %}

newsapp/templates/newsapp/signin.html
{% extends "newsapp/base.html" %}

{% load static %}

{% block moreRef %}
<link rel="stylesheet" href="{% static 'newsapp/form.css' %}">
{% endblock %}

{% block content %}

<form method="post" id="signin_form">
	{% csrf_token %}
	<h2>Log In</h2>
	<label for="username">Username:</label>
	<input type="text" id="username" name="username">
	<label for="password">Password:</label>
	<input type="password" id="password" name="password">
	<input type="submit" name="signin_submit" id="signin_submit">
</form>

{% endblock %}

newsapp/templates/newsapp/signup.html
{% extends "newsapp/base.html" %}

{% load static %}

{% block moreRef %}
<script src="{% static 'newsapp/ajax_form.js' %}"></script>
<link rel="stylesheet" href="{% static 'newsapp/form.css' %}">
{% endblock %}

{% block content %}
<div id="signup_status">
	
</div>
<form method="post" id="signup_form">
	{% csrf_token %}
	
	<fieldset id="personalia">
		<legend>Personalia:</legend>
		<label for="fname">First name:</label>
		<input type="text" id="fname" name="fname">
		<label for="lname">Last name:</label>
		<input type="text" id="lname" name="lname">
		<label for="username">Username:</label>
		<input type="text" name="username">
		<label for="password">Password:</label>
		<input type="password" name="password">
	</fieldset>
	<!-- <fieldset>
		<legend>Affiliation:</legend>
		<label for="college">College:</label>
		<input list="college-names" id="college" name="college">
		<datalist id="college-names">
			<option value="College of Agriculture">
			<option value="College of Education">
			<option value="College of Engineering">
			<option value="Exploratory Studies">
			<option value="College of Health and Human Sciences">
			<option value="College of Liberal Arts">
			<option value="Krannert School of Management">
			<option value="College of Pharmacy">
			<option value="Purdue Polytechnic Institute">
			<option value="College of Science">
			<option value="College of Veterinary Medicine">
			<option value="Honors College">
			<option value="The Graduate School">
		</datalist>
	</fieldset>
	<label for="news-category">Choose your interested news categories:</label><br>
	<select id="news-category" name="news-category" multiple>
		<option value="research">Research</option>
		<option value="teaching_and_learning">Teaching and Learning</option>
		<option value="sports">Sports</option>
		<option value="benefits">Benefits</option>
	</select> -->
	<input id="signup_submit" type="button" value="Submit">
</form>
{% endblock %}

newsapp/templates/newsapp/trending.html
{% extends "newsapp/base.html" %}

{% block content %}
  <ul>
		{% for trending_news in trending_news_list %}
    <li><a href="{% url 'newsapp:news_article_detail' trending_news.id %}">{{ trending_news.title }}</a></li>
		{% endfor %}
	</ul>
{% endblock %}